name: Validate HTML

on:
  push:
    branches: [main]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Fix permissions for html-validator
        run: chmod +x node_modules/.bin/html-validator

      - name: Validate HTML files
        run: npx html-validator --file=index.html --verbose
