name: Validate HTML & JS

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Validate HTML
        run: npx html-validator --file=index.html --verbose

      - name: Lint JavaScript
        run: npx eslint script.js
