name: Validate HTML

on:
  push:
    branches: [main]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install HTML Validator
        run: npm install -g html-validator-cli

      - name: Validate index.html
        run: html-validator --file=index.html --verbose
